#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

if [ -f "/opt/firstboot" ]; then
	echo "First time booting..."
	/sbin/resize2fs /dev/block/mtd/by-name/linuxroot
	rm /opt/firstboot
fi

test -f /etc/ssh/ssh_host_dsa_key #|| dpkg-reconfigure openssh-server

# cd /opt/
# chmod +x app
# ./app &
